//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coolex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("coolex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toVersion = &apos;&apos;;
        ///length = 1;
        ///
        ///search = Geotab_NewObject();
        ///
        ///date = %date;
        ///Geotab_SetStr(search:&apos;fromDate&apos;:%char(date:*iso));
        ///
        ///Dow (length &gt; 0);
        ///  Geotab_Close(data);
        ///
        ///  data = Geotab_GetFeed(authinfo:&apos;ExceptionEvent&apos;:500:toVersion:search);
        ///  toVersion = Geotab_StringAt(data:&apos;result.toVersion&apos;);
        ///
        ///  //Amount of elements returned
        ///  length = Geotab_GetCount(data);
        ///
        ///  If (length &gt; 0);
        ///    Dsply (&apos;Count: &apos; + %char(length) + &apos;-&apos; + %trimr(toVersion));
        ///  Else;
        ///    Geotab_Close(data);
        ///    Leave;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         
        ///
        ///		//***************************************************
        ///		private CoolexType TokenList = new CoolexType(Type.BLOCK, &quot;&quot;, 0);
        ///		public List&lt;CoolexType&gt; GetTokens() =&gt; TokenList.Block;
        ///
        ///		//***************************************************
        ///        private int printIndex = -1;
        ///        public void PrintBlock(List&lt;CoolexType&gt; Block)
        ///        {
        ///            printIndex++;
        ///            foreach (CoolexType Token in Block)
        ///            {
        ///                Console.WriteLine(&quot;&quot;.PadRight(printIndex, &apos;\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     class CoolexType
        ///    {
        ///        public List&lt;CoolexType&gt; Block;
        ///        public CoolexLex.Type Type;
        ///        public string Value;
        ///		public int Line;
        ///
        ///        public CoolexType(CoolexLex.Type type, string value, int line)
        ///        {
        ///            Type = type;
        ///            Value = value;
        ///			Line = line;
        ///            Block = null;
        ///        }
        ///    }
        ///
        ///	class ParseError 
        ///	{
        ///		public int Line;
        ///		public string Text;
        ///
        ///		public ParseError(int line, string text) {
        ///		  this.Line = line;
        ///		  this.Text = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TypeClass {
            get {
                return ResourceManager.GetString("TypeClass", resourceCulture);
            }
        }
    }
}
